<a href="https://colab.research.google.com/github/zain4cs/Encoding_Methods/blob/main/Column_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np

________________________

**ML Libraries**

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

_____________

In [20]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [21]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [22]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

_________________________

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [24]:
X_train.head()

    age  gender  fever   cough       city
85   16  Female  103.0    Mild  Bangalore
5    84  Female    NaN    Mild  Bangalore
19   42  Female    NaN  Strong  Bangalore
21   73    Male   98.0    Mild  Bangalore
69   73  Female  103.0    Mild      Delhi

In [26]:
# Adding Simple Imputer to Fever Coumn

si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)