<a href="https://colab.research.google.com/github/zain4cs/Encoding_Methods/blob/main/One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/cars.csv")
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [67]:
# Check the number of Brands
df['brand'].nunique()

32

In [68]:
df['owner'].value_counts().reset_index()

                  owner  count
0           First Owner   5289
1          Second Owner   2105
2           Third Owner    555
3  Fourth & Above Owner    174
4        Test Drive Car      5

In [69]:
df['fuel'].value_counts().reset_index()

     fuel  count
0  Diesel   4402
1  Petrol   3631
2     CNG     57
3     LPG     38

_______________________

**One Hot Encoding Using Pandas**

In [70]:
pd.get_dummies(df, columns=['fuel', 'owner'], dtype="int")

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

________________________________

**N-1 One Hot Encoder**

In [71]:
pd.get_dummies(df, columns=['fuel','owner'], drop_first=True, dtype='int')

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

___________________________

**(One Hot Encoder) Using sklearn**

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1],
                                                    test_size=0.2,
                                                    random_state=42)

In [74]:
X_test.head().reset_index()

   index   brand  km_driven    fuel         owner
0   1971   Honda     110000  Petrol   Third Owner
1   4664    Tata     291977  Diesel   First Owner
2   5448  Maruti      70000  Diesel   First Owner
3   3333   Honda     120000  Petrol  Second Owner
4   2316  Maruti      69000  Diesel  Second Owner

________________________

**Apply Encoder**

In [75]:
from sklearn.preprocessing import OneHotEncoder

In [76]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [77]:
np.hstack((X_train[['km_driven','km_driven']].values,X_train_new)).shape

(6502, 9)

In [78]:
X_test_new

array([[0, 0, 1, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], dtype=int32)

__________________________

**(One Hot Encoder) with top Categories**

In [79]:
count = df['brand'].value_counts()

In [80]:
threshold=100

In [81]:
rep = count[count <= threshold].index

In [90]:
df['brand'] = df['brand'].replace(rep,'Uncommon')
pd.get_dummies(df['brand'], dtype='int')

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Uncommon,Volkswagen
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,0,1,0,0,0